export const ERROR_CODES = {
    VALIDATION_ERROR: "VALIDATION_ERROR",
    NOT_FOUND: "NOT_FOUND",
    DUPLICATE: "DUPLICATE",
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    SERVER_ERROR: "SERVER_ERROR",
    IDEMPOTENT_CONFLICT: "IDEMPOTENT_CONFLICT"
  } as const;
  
  export type ErrorCode = keyof typeof ERROR_CODES;
  